spring:
  application:
    name: 工作流
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/workflow?autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=GMT
    username: root
    password: root
    driver-class: com.mysql.cj.jdbc.Driver
  activiti:
    check-process-definitions: true #自动检查、部署流程定义文件
    database-schema-update: true #自动更新数据库结构
    history-level: full #保存历史数据级别设置为full最高级别，便于历史数据的追溯
    # process-definition-location-prefix: classpath:/processes/ #流程定义文件存放目录
    # process-definition-location-suffixes: #流程文件格式
    #  - **.bpmn20.xml
    #  - **.bpmn
server:
  port: 8030

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
debug: true
