spring:
  application:
    name: 权限管理
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/auth?autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=UTF-8&useSSL=true&serverTimezone=GMT
    username: root
    password: root
    driver-class: com.mysql.cj.jdbc.Driver
server:
  port: 8010

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
jwt:
  header: Authorization
  token-prefix: Bearer
  key: JldM90LCIQNZ3cQXrER3Jqyq3bkXttLNNVaTsc1TaEPQ9p1gZM8Z0TtvZL88S0bb
  expires-at: 120 # 分钟
  audience: web
debug: true
